name: Trigger Blog Deployment

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout blog repo
      uses: actions/checkout@v2
      with:
        repository: darnocer/blog
        token: ${{ secrets.BLOG_TRIGGER_TOKEN }}
        path: blog

    - name: Create empty commit and push
      run: |
        cd blog
        git config user.name "GitHub Actions Bot"
        git config user.email "darnocer@gmail.com"
        git commit --allow-empty -m "Triggering Vercel Deployment"
        git push
