name: Update Content Submodule and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog repository # checkout main blog repo
        uses: actions/checkout@v2
        with:
          repository: darnocer/blog
          token: ${{ secrets.BLOG_UPDATE }} #PAT secret (Github)
          submodules: 'recursive'  # Ensure submodules are initialized and updated.

      - name: Update content submodule # updates content submodule in the blog repo
        run: |
          git submodule update --remote content
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add content
          git commit -m "Update content submodule"
          git push

      - name: Trigger Vercel Deployment # trigger vercel deployment from blog repo with updated content submodule
        run: |
          curl -X POST ${{ secrets.VERCEL_HOOK }}
