name: Trigger Vercel Deployment

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment on Vercel
        run: |
          curl -X POST ${{ secrets.VERCEL_HOOK }}
