name: Update Content and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the 'blog' repo
      - name: Checkout blog repository
        uses: actions/checkout@v2
        with:
          repository: darnocer/blog
          token: ${{ secrets.BLOG_UPDATE }}

      # Update the 'content' submodule
      - name: Update content submodule
        run: |
          git submodule update --remote content
          git add content
          git commit -m "Update content submodule"
          git push

      # Trigger a Vercel deploy
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST ${{ secrets.VERCEL_HOOK }}
